M48
; DRILL file {KiCad 7.0.6-7.0.6~ubuntu22.04.1} date lun. 07 août 2023 17:02:54
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-08-07T17:02:54+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.6-7.0.6~ubuntu22.04.1
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0157
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0394
%
G90
G05
T1
X5.12Y-3.47
X5.18Y-3.62
T2
X4.923Y-3.3148
X4.923Y-3.4148
X4.923Y-3.5148
X4.923Y-3.6148
T0
M30
