M48
; DRILL file {KiCad 7.0.6-7.0.6~ubuntu22.04.1} date lun. 14 août 2023 10:47:37
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-08-14T10:47:37+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.6-7.0.6~ubuntu22.04.1
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0157
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0394
%
G90
G05
T1
X5.12Y-3.29
X5.95Y-3.25
X6.31Y-3.33
T2
X5.028Y-3.08
X5.028Y-3.18
X5.028Y-3.28
X5.028Y-3.38
T0
M30
